### ISSUE TITLE
Request: KSP2 Kerbol system option

### ISSUE THREAD

**Issue by Aquilux** [Krafpy/KSP-MGA-Planner#34]
KSP 2 uses the same kerbol system, but it's epoch is off by 1 year. Could we get a copy of stock with the year ticked over for KSP2 to make it easier for newer users?

**Comment by nmisyats** [comment]
Just to be sure that I understood correctly: all orbital elements of every bodies remain the same but the epoch to which they correspond is not 0 UT but +1/-1 year UT ? Is it +1 or -1 ?

**Comment by Aquilux** [comment]
Sorry for not replying, I'll boot up new games on both this weekend and compare to give you an update if I remember to.

**Comment by schlosrat** [comment]
I believe there may be a bit more to it than just the epoch difference. You may find some info here: https://kerbal-space-program-2.fandom.com/wiki/Planetary_Systems. I've heard that in KSP2 Dres's orbit may be different, so be sure to check out the orbital characteristics for Dres: https://kerbal-space-program-2.fandom.com/wiki/Dres.

EDIT: Confirmed. Dres's orbital characteristics are different. See KSP1 values here (though I'm certain you've got them anyway) https://wiki.kerbalspaceprogram.com/wiki/Dres. The KSP2 data seems to show that the SMA is the same, but Ap and Pe are different, yet it goes on to state the eccentricity is the same (not possible if Ap and Pe are different).

KSP2 orbital info for Dres
Semi Major Axis 40839348203 m
Apoapsis 46499453692.435 m
Periapsis 34656042713.565 m
Eccentricity 0.145
Inclination 5°
Argument of Periapsis 90°
Longitude of the Ascending Node 280°
Orbital Period 47893063.138593 s
Mean Orbital Velocity 5329.520649 ms-1
Apoapsis Velocity 4629.844129 ms-1
Periapsis Velocity 6200.200617 ms-1
Synchronous Orbit 732244.439968 m
Semi-Synchronous Orbit 410219.644235 m

vs. KSP1 Dres orbital info
Semi-major axis | 40 839 348 203 m [Note 1]
Apoapsis | 46 761 053 692 m
Periapsis | 34 917 642 714 m
Orbital eccentricity | 0.145
Orbital inclination | 5 °
Argument of periapsis | 90 °
Longitude of the ascending node | 280 °
Mean anomaly | 3.14 rad (at 0s UT)
Sidereal orbital period | 47 893 063 s
2 217 d 1 h 37 m 43.1 s
Synodic orbital period | 11 392 903.3 s
Orbital velocity | 4 630 - 6 200 m/s

**Comment by schlosrat** [comment]
KSP1 starts at Year 1, Day 1, but KSP2 starts at Year 0, Day 0, so they are off by 1 year and 1 day at least. Possibly also by 1 hour, etc.

**Comment by nmisyats** [comment]
Isn't it just a change in the way the date is displayed in KSP2 ? i.e. KSP1 shows the date/time at the first instant in the game as Y1 D1 00:00:00 while KSP2 shows Y0 D0 00:00:00.

**Comment by schlosrat** [comment]
I believe it's an actual change and not merely a display change. How can we confirm this?

**Comment by nmisyats** [comment]
Comparing the positions of the planets at the same "elapsed times from start" may confirm. For example, taking a screenshot of the planets positions on a new game's start (UT = 0) in KSP1 (Y1 D1 00:00:00) and KSP2 (Y0 D0 00:00:00), then another pair of screenshots after some fixed amount of time for both games (e.g. UT+10 days, +100 days, +1 year and +2 years), writing down the displayed dates for each. If the planets' positions match then it's just a display change. Otherwise then there is a change in the reference epoch (or could be something else, but the orbital characteristics of the main planets seem to remain the same according to the wiki). This should be visible immediatly by comparing just the positions at UT = 0 in both games. Comparing with days and years later will allow to deduce if it's +1 or -1 year (if it's a more precise value it will be harder however).
I don't have KSP2, so I can't test it, but if you have it and have the time to make the experiment, please post your results.

I would actually be surprised if it's more than just a display change, because both the year and day are shifted by -1 from KSP1 to KSP2.

**Comment by schlosrat** [comment]
OK, here are some images. I did my best to start them with Kerbol focused and so the first image has Kerbin at 90 degrees (due East of Kerbol looking top-down). The times are pretty close to what you asked for and are visible in each frame.

KSP1_Y1_D1: https://i.imgur.com/BRTEj9j.png
KSP1_Y1_D10: https://i.imgur.com/fNOulVp.png
KSP1_Y1_D100: https://i.imgur.com/fi6F50G.png
KSP1_Y2_D3: https://i.imgur.com/rhpYgbK.png
KSP1_Y3_D1: https://i.imgur.com/oPaNoCA.png

KSP2_Y0_D0: https://i.imgur.com/qDINxw7.png
KSP2_Y0_D10: https://i.imgur.com/nLUbWZZ.png
KSP2_Y0_D100: https://i.imgur.com/r6CKAZP.png
KSP2_Y1_D1: https://i.imgur.com/3rBFmq8.png
KSP2_Y2_D0: https://i.imgur.com/nxPJKPX.png
KSP2_Y3_D1: https://i.imgur.com/8lX1DgX.png

I think I may go back and make a video of the clock rolling over from year to year. I observed that with KSP1 this occurs (as expected) on day 426 plus a bit, but I think I saw that in KSP2 it was happening on day 425. This seems to support the hypothesis that it may be just a display/counting offset - at least as far as days go since in KSP1 the roll over takes you to Day 1 of the next year and in KSP2 it takes you to Day 0.

**Comment by schlosrat** [comment]
Here are overlays from Photoshop with the KSP1 image as the base layer and the corresponding KSP2 image above that with 70% opacity. I've done no rotation or scaling on either image, but I did eyeball placing the KSP2 image so that Kerbol is aligned in both images. This seems to further corroborate the hypothesis that it's just a display/counting difference and not actually an epoch difference.

KSP1_Y1_D1_vs_KSP2_Y0_D0: https://i.imgur.com/UADk72n.png
KSP1_Y1_D10_vs_KSP2_Y0_D10: https://i.imgur.com/bmGW8ur.png
KSP1_Y1_D100_vs_KSP2_Y0_D100: https://i.imgur.com/OMUk8Q3.png
KSP1_Y2_D3_vs_KSP2_Y1_D1: https://i.imgur.com/4bsY32Q.png
KSP1_Y3_D1_vs_KSP2_Y2_D0: https://i.imgur.com/SAVRYFS.png

**Comment by nmisyats** [comment]
Thank you very much for your help !
The planets' positions seem to match perfectly at Y1 D1 in KSP1 and Y0 D0 in KSP2. So this means (if my logic is correct.) that it's just a display change. This also seems to make sense with the fact that in the KSP2 screenshots the game shows "UT _**T+**_ 000y...".

If we want to have the final answer maybe the best is just to ask the devs on the forum, but for me this experiment in convincing enough.

I'll add an option to switch the date/time display between year/day counts starting at 1 (KSP1) and elapsed time based (KSP2).
I'll also add a KSP2 Stock option with the correct orbital elements for Dres.

**Comment by schlosrat** [comment]
Excellent! Thanks!

It might be a good idea to double-check all the planets just to be sure since there are some differences with Dres, but it certainly seems to be primarily just a display issue - which is very nice to know!

**Comment by nmisyats** [comment]
@schlosrat The values for periapsis (PE) and apoapsis (AP) for Dres don't match with the SMA on the KSP2 wiki. The SMA should be equal to (PE + AP) / 2. But:

- Dres orbital elements from [KSP1 wiki](https://wiki.kerbalspaceprogram.com/wiki/Dres):
  - AP = 46761053692
  - PE = 34917642714
  - (AP + PE) / 2 = **40839348203**
  - SMA = **40839348203**
  - (AP + PE) / 2 = SMA : **OK**

- Dres orbial elements from [KSP2 wiki](https://kerbal-space-program-2.fandom.com/wiki/Dres):
  - AP = 46499453692.435
  - PE = 34656042713.565
  - (AP + PE) / 2 = 40577748203
  - SMA = 40839348203
  -  (AP + PE) / 2 **!=** SMA : **mismatch**

Dres seems to be not the only one in this case, I quickly checked Eve and it turns out there is also a mismatch:

(9669411389.44 + 9472757698.56) / 2 = 9571084544 **!=** 9832684544

I don't know where they've got their values on the KSP2 wiki, since they have more decimals than the KSP1 wiki. Maybe experimentally in game ? But then why do they have the SMA value for KSP1 ?

Are there any game file for KSP2 that contains the exact planet information ?

**Comment by schlosrat** [comment]
[Info   :Flight Plan] Moho:
[Info   :Flight Plan] Apoapsis:     6315765964.8
[Info   :Flight Plan] Periapsis:    4210510643.2
[Info   :Flight Plan] eccentricity: 0.2
[Info   :Flight Plan] inclination:  7
[Info   :Flight Plan] SMA:          5263138304
[Info   :Flight Plan] LAN:          70
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       102 d 3:29:14.22

[Info   :Flight Plan] Eve:
[Info   :Flight Plan] Apoapsis:     9931011389.44
[Info   :Flight Plan] Periapsis:    9734357698.56
[Info   :Flight Plan] eccentricity: 0.01
[Info   :Flight Plan] inclination:  2.1
[Info   :Flight Plan] SMA:          9832684544
[Info   :Flight Plan] LAN:          15
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       261 d 5:39:55.15

[Info   :Flight Plan] Gilly:
[Info   :Flight Plan] Apoapsis:     48825000
[Info   :Flight Plan] Periapsis:    14175000
[Info   :Flight Plan] eccentricity: 0.55
[Info   :Flight Plan] inclination:  12
[Info   :Flight Plan] SMA:          31500000
[Info   :Flight Plan] LAN:          80
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       17 d 5:56:27.38

[Info   :Flight Plan] Kerbin:
[Info   :Flight Plan] Apoapsis:     13599840256
[Info   :Flight Plan] Periapsis:    13599840256
[Info   :Flight Plan] eccentricity: 0
[Info   :Flight Plan] inclination:  0
[Info   :Flight Plan] SMA:          13599840256
[Info   :Flight Plan] LAN:          0
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       1 y 24.62

[Info   :Flight Plan] Mun:
[Info   :Flight Plan] Apoapsis:     12000000
[Info   :Flight Plan] Periapsis:    12000000
[Info   :Flight Plan] eccentricity: 0
[Info   :Flight Plan] inclination:  0
[Info   :Flight Plan] SMA:          12000000
[Info   :Flight Plan] LAN:          0
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       6 d 2:36:24.38

[Info   :Flight Plan] Minmus:
[Info   :Flight Plan] Apoapsis:     47000000
[Info   :Flight Plan] Periapsis:    47000000
[Info   :Flight Plan] eccentricity: 0
[Info   :Flight Plan] inclination:  6
[Info   :Flight Plan] SMA:          47000000
[Info   :Flight Plan] LAN:          78
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       49 d 5:15:10.52

[Info   :Flight Plan] Duna:
[Info   :Flight Plan] Apoapsis:     21783189182.464
[Info   :Flight Plan] Periapsis:    19669121345.536
[Info   :Flight Plan] eccentricity: 0.051
[Info   :Flight Plan] inclination:  0.06
[Info   :Flight Plan] SMA:          20726155264
[Info   :Flight Plan] LAN:          135.5
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       1 y 375 d 3:18:00.14

[Info   :Flight Plan] Ike:
[Info   :Flight Plan] Apoapsis:     3296000
[Info   :Flight Plan] Periapsis:    3104000
[Info   :Flight Plan] eccentricity: 0.03
[Info   :Flight Plan] inclination:  0.2
[Info   :Flight Plan] SMA:          3200000
[Info   :Flight Plan] LAN:          0
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       3 d 0:11:57.86

[Info   :Flight Plan] Dres:
[Info   :Flight Plan] Apoapsis:     46761053692.435
[Info   :Flight Plan] Periapsis:    34917642713.565
[Info   :Flight Plan] eccentricity: 0.145
[Info   :Flight Plan] inclination:  5
[Info   :Flight Plan] SMA:          40839348203
[Info   :Flight Plan] LAN:          280
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       5 y 86 d 4:57:43.14

[Info   :Flight Plan] Jool:
[Info   :Flight Plan] Apoapsis:     72212238336
[Info   :Flight Plan] Periapsis:    65334882304
[Info   :Flight Plan] eccentricity: 0.05
[Info   :Flight Plan] inclination:  1.304
[Info   :Flight Plan] SMA:          68773560320
[Info   :Flight Plan] LAN:          52
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       11 y 158 d 2:45:12.11

[Info   :Flight Plan] Laythe:
[Info   :Flight Plan] Apoapsis:     27184000
[Info   :Flight Plan] Periapsis:    27184000
[Info   :Flight Plan] eccentricity: 0
[Info   :Flight Plan] inclination:  0
[Info   :Flight Plan] SMA:          27184000
[Info   :Flight Plan] LAN:          0
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       2 d 2:43:00.88

[Info   :Flight Plan] Vall:
[Info   :Flight Plan] Apoapsis:     43152000
[Info   :Flight Plan] Periapsis:    43152000
[Info   :Flight Plan] eccentricity: 0
[Info   :Flight Plan] inclination:  0
[Info   :Flight Plan] SMA:          43152000
[Info   :Flight Plan] LAN:          0
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       4 d 5:26:02.09

[Info   :Flight Plan] Tylo:
[Info   :Flight Plan] Apoapsis:     68500000
[Info   :Flight Plan] Periapsis:    68500000
[Info   :Flight Plan] eccentricity: 0
[Info   :Flight Plan] inclination:  0.025
[Info   :Flight Plan] SMA:          68500000
[Info   :Flight Plan] LAN:          0
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       9 d 4:52:06.36

[Info   :Flight Plan] Bop:
[Info   :Flight Plan] Apoapsis:     131519750
[Info   :Flight Plan] Periapsis:    125480250
[Info   :Flight Plan] eccentricity: 0.0235
[Info   :Flight Plan] inclination:  15
[Info   :Flight Plan] SMA:          128500000
[Info   :Flight Plan] LAN:          10
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       25 d 1:15:07.43

[Info   :Flight Plan] Pol:
[Info   :Flight Plan] Apoapsis:     210624206.5
[Info   :Flight Plan] Periapsis:    149155793.5
[Info   :Flight Plan] eccentricity: 0.17085
[Info   :Flight Plan] inclination:  4.25
[Info   :Flight Plan] SMA:          179890000
[Info   :Flight Plan] LAN:          2
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       41 d 4:31:42.62

[Info   :Flight Plan] Eeloo:
[Info   :Flight Plan] Apoapsis:     113549713200
[Info   :Flight Plan] Periapsis:    66687926800
[Info   :Flight Plan] eccentricity: 0.26
[Info   :Flight Plan] inclination:  6.15
[Info   :Flight Plan] SMA:          90118820000
[Info   :Flight Plan] LAN:          50
[Info   :Flight Plan] Epoch:        0
[Info   :Flight Plan] Period:       17 y 24 d 3:50:08.40

**Comment by schlosrat** [comment]
```cs
if (_currentTarget != null)
{
#if DEBUG
    FlightPlanPlugin.Logger.LogInfo($"{_currentTarget.Name}:");
    FlightPlanPlugin.Logger.LogInfo($"Apoapsis:     {_currentTarget.Orbit.Apoapsis}");
    FlightPlanPlugin.Logger.LogInfo($"Periapsis:    {_currentTarget.Orbit.Periapsis}");
    FlightPlanPlugin.Logger.LogInfo($"eccentricity: {_currentTarget.Orbit.eccentricity}");
    FlightPlanPlugin.Logger.LogInfo($"inclination:  {_currentTarget.Orbit.inclination}");
    FlightPlanPlugin.Logger.LogInfo($"SMA:          {_currentTarget.Orbit.semiMajorAxis}");
    FlightPlanPlugin.Logger.LogInfo($"LAN:          {_currentTarget.Orbit.longitudeOfAscendingNode}");
    FlightPlanPlugin.Logger.LogInfo($"Epoch:        {_currentTarget.Orbit.epoch}");
    FlightPlanPlugin.Logger.LogInfo($"Period:       {FPUtility.SecondsToTimeString(_currentTarget.Orbit.period)}");
#endif
}
```

**Comment by schlosrat** [comment]
Will this help? I don't know what game file this info is in, but I certainly know how to pull it out on demand!

**Comment by nmisyats** [comment]
Thank you very much for all the data !

The AP et PE values are very close to those of KSP1. Actually, a few bodies just have a difference in their AP/PE of about 20 meters. Except Bop which for some reason has about 27177 kilometers of difference...

I added the KSP2 solar system (see 0af3ed78270af2e8c43240fce85547522d3a8962), and an option to switch between the KSP1 date display mode and the KSP2 one (the "Show dates as elapsed time" option under the solar system view, which is automatically enabled for KSP2).

I consider this issue resolved. Don't hesitate to open a new one if you notice any problem.
